name: Add unclassified label to closed issues without a milestone

on:
  issues:
    types: [closed]

jobs:
  add-unclassified-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Unclassified label
        uses: actions/github-script@v6
        if: github.event.pull_request.milestone == null && github.event.pull_request.merged == true
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const labelsToAdd = ["unclassified"];
            const octokit = new Octokit();
            await octokit.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: labelsToAdd
            });
