name: Add unclassified label to closed issues without a milestone

on:
  issues:
    types: [closed]

jobs:
  add-unclassified-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Unclassified label
        uses: actions/github-script@v6
        if: github.event.issue.milestone == null && github.event.issue.resolution != 'not_planned'
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const labelsToAdd = ["unclassified"];
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: labelsToAdd
            });
