name: Add unclassified label to merged PRs without a milestone

on:
  pull_request:
    types: [closed]

jobs:
  add-unclassified-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Unclassified label
        uses: actions/github-script@v6
        if: github.event.pull_request.milestone == null && github.event.pull_request.merged == true
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const labelsToAdd = ["unclassified"];
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: labelsToAdd
            });
